apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: colors
spec:
  hosts:
  - "colors.demo4591.codefresh.io"
  gateways:
  - colors
  http:
  - ae8abd6f99e0611e9802a06a9ed4785d-1663402401.us-west-2.elb.amazonaws.com
